name: Run AQI Fetch Daily

on:
  schedule:
    - cron: '0 19 * * *'  # 12:00 AM PKT = 7:00 PM UTC
  workflow_dispatch:       # Allow manual trigger from GitHub

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Set environment variable
        run: echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" >> $GITHUB_ENV

      - name: Run the script
        run: python fetch_aqi.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add karachi_air_quality.csv
          git commit -m "Update CSV with daily AQI data" || echo "No changes to commit"
          git push
